server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.201.17:3306/biblioteca?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Argentina/Buenos_Aires
    username: Jet
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none   # o update/create-drop seg√∫n tu caso
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    biblioteca.biblioteca: DEBUG
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
